repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: pretty-format-json
        args: [ '--autofix' ]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: make format
        language: system
        pass_filenames: false
      - id: version-check
        name: Version check (no writes)
        entry: version-manager check
        language: python
        pass_filenames: false
        always_run: true
        stages: [ pre-push ]
