repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: pretty-format-json
        args: [ '--autofix' ]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: make format
        language: system
        pass_filenames: false
      - id: auto-version-changelog
        name: Auto Version & Changelog
        entry: version-manager
        language: python
        types: [python]
        pass_filenames: false
